version: "3"
networks:
  net:
    driver: bridge
volumes:
    backup_bd:
    #pgadmin_data:
services:
  bd_backup:
    image: postgres:12
    container_name: postgre_cont
    volumes:
      - backup_bd:/var/lib/backup_postgresql
    environment:
      #POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - net
  pgadmin:
    container_name: pgadmin_cont
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    #volumes:
    #  - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - net





